from datetime import date
from decimal import Decimal

from .models import Availability, Product, RelatedProduct, RelationType, SalePrice

BASE_URL = "https://loopinthreads.example.com/products"

CATALOG: list[Product] = [
    Product(
        id="SKU-SNK-001",
        title="Loopin Trail Runner Sneakers",
        description="Lightweight everyday trainers with a breathable knit upper and cushioned sole, built for city walking and light trail use.",
        link=f"{BASE_URL}/trail-runner-sneakers",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Footwear > Sneakers",
        availability=Availability.IN_STOCK,
        inventory_quantity=42,
        price_inr=Decimal("3499.00"),
        popularity_score=4.4,
        review_count=212,
        review_rating=4.3,
        related_products=[
            RelatedProduct(relation_type=RelationType.ACCESSORY, target_id="SKU-SOX-010"),
            RelatedProduct(relation_type=RelationType.UPSELL, target_id="SKU-SNK-002"),
        ],
    ),
    Product(
        id="SKU-SNK-002",
        title="Loopin Trail Runner Pro Sneakers",
        description="The Pro version of our Trail Runner with a reinforced outsole, water-resistant coating, and memory-foam insole.",
        link=f"{BASE_URL}/trail-runner-pro-sneakers",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Footwear > Sneakers",
        availability=Availability.IN_STOCK,
        inventory_quantity=18,
        price_inr=Decimal("4999.00"),
        popularity_score=4.6,
        review_count=64,
        review_rating=4.5,
    ),
    Product(
        id="SKU-SOX-010",
        title="Loopin Cushion Ankle Socks (Pack of 3)",
        description="Moisture-wicking ankle socks with reinforced heel cushioning, sold as a pack of three pairs.",
        link=f"{BASE_URL}/cushion-ankle-socks",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Clothing Accessories > Socks",
        availability=Availability.IN_STOCK,
        inventory_quantity=150,
        price_inr=Decimal("499.00"),
        popularity_score=4.1,
        review_count=98,
        review_rating=4.0,
    ),
    Product(
        id="SKU-JKT-020",
        title="Loopin All-Weather Windbreaker Jacket",
        description="Packable windbreaker with a water-resistant shell, adjustable hood, and zip pockets. Suits monsoon commutes and light hikes.",
        link=f"{BASE_URL}/all-weather-windbreaker",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Clothing > Outerwear",
        availability=Availability.IN_STOCK,
        inventory_quantity=27,
        price_inr=Decimal("2999.00"),
        popularity_score=4.2,
        review_count=41,
        review_rating=4.2,
    ),
    Product(
        id="SKU-JNS-030",
        title="Loopin Straight Fit Denim Jeans",
        description="Mid-rise straight fit jeans in rigid cotton denim with a five-pocket construction.",
        link=f"{BASE_URL}/straight-fit-denim-jeans",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Clothing > Jeans",
        availability=Availability.IN_STOCK,
        inventory_quantity=35,
        price_inr=Decimal("1999.00"),
        popularity_score=4.0,
        review_count=76,
        review_rating=3.9,
        related_products=[
            RelatedProduct(relation_type=RelationType.ACCESSORY, target_id="SKU-BLT-040"),
        ],
    ),
    Product(
        id="SKU-BLT-040",
        title="Loopin Leather Belt",
        description="Full-grain leather belt with a matte buckle, available in a single classic brown finish.",
        link=f"{BASE_URL}/leather-belt",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Clothing Accessories > Belts",
        availability=Availability.IN_STOCK,
        inventory_quantity=60,
        price_inr=Decimal("799.00"),
        popularity_score=3.8,
        review_count=29,
        review_rating=4.1,
    ),
    Product(
        id="SKU-CAP-050",
        title="Loopin Classic Cap",
        description="Structured cotton twill cap with an embroidered logo and adjustable back strap.",
        link=f"{BASE_URL}/classic-cap",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Clothing Accessories > Hats",
        availability=Availability.OUT_OF_STOCK,
        inventory_quantity=0,
        price_inr=Decimal("599.00"),
        popularity_score=3.6,
        review_count=15,
        review_rating=3.8,
    ),
    Product(
        id="SKU-BAG-060",
        title="Loopin Everyday Backpack",
        description="20L water-resistant backpack with a padded 15-inch laptop sleeve and a quick-access front pocket.",
        link=f"{BASE_URL}/everyday-backpack",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Handbags, Wallets & Cases > Backpacks",
        availability=Availability.IN_STOCK,
        inventory_quantity=22,
        price_inr=Decimal("2499.00"),
        popularity_score=4.5,
        review_count=133,
        review_rating=4.4,
        related_products=[
            RelatedProduct(relation_type=RelationType.CROSS_SELL, target_id="SKU-BTL-070"),
        ],
    ),
    Product(
        id="SKU-BTL-070",
        title="Loopin Insulated Water Bottle",
        description="600ml double-wall stainless steel bottle that keeps drinks cold for 18 hours or hot for 8.",
        link=f"{BASE_URL}/insulated-water-bottle",
        brand="Loopin Threads",
        product_category="Apparel & Accessories > Drinkware > Water Bottles",
        availability=Availability.IN_STOCK,
        inventory_quantity=80,
        price_inr=Decimal("899.00"),
        sale_price=SalePrice(
            amount_inr=Decimal("699.00"),
            starts_on=date(2026, 9, 1),
            ends_on=date(2026, 9, 30),
        ),
        popularity_score=4.3,
        review_count=52,
        review_rating=4.2,
    ),
]
